spring:
  application:
    name: eureka-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
    register-with-eureka: false # 默认会向 Eureka 中注册，设为 false 不注册
server:
  port: 9012
