spring:
  application:
    name: eureka-server
server:
  port: 10011
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:10012/eureka/,http://peer3:10013/eureka/
