spring:
  application:
    name: eureka-server
server:
  port: 10012
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:10011/eureka/,http://peer3:10013/eureka/
