spring:
  application:
    name: eureka-server
server:
  port: 10013
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:10011/eureka/,http://peer2:10012/eureka/
